version: "3.7"
services:
    flask_1:
        build: ./flask
        container_name: flask1
        expose:
            - 5000
    proxy:
        build: ./nginx
        container_name: nginx
        ports:
            - "80:80"
        restart: "unless-stopped"
